[project]
name = "git-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "cloudflare>=4.0.0",
    "openai>=1.12.0",
    "requests>=2.32.3",
    "tree-sitter>=0.24.0",
]
